---
shared:
  image: node:16
  environment:
    SD_TEMPLATE_PATH: ./template.yaml
jobs:
  validate_template:
    requires: [~pr, ~commit]
    steps:
      - install_prerequisites: npm install -g screwdriver-template-main
      - validate_template: template-validate

  publish_template:
    requires: [validate_template]
    steps:
      - install_prerequisites: npm install -g screwdriver-template-main
      - test: cat $SD_TEMPLATE_PATH
      - help: template-publish --help
      - publish: template-publish --json --tag stable
      - autotag: template-tag --name sd/dind --tag latest
